// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/*
await Firebase.initializeApp(
  options: DefaultFirebaseOptions.currentPlatform,
);
*/
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB36RdgEfaYp6W595HLE0uhz2ShilysI0E',
    appId: '1:596845297819:web:33e9e8613dc6ced30a063e',
    messagingSenderId: '596845297819',
    projectId: 'laundromate-2e111',
    authDomain: 'laundromate-2e111.firebaseapp.com',
    storageBucket: 'laundromate-2e111.appspot.com',
    measurementId: 'G-TFF30NT03C',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAUF5vVt8-X2oypuu_h5SWcE7WRs15Y1ig',
    appId: '1:596845297819:android:73649de62b31323d0a063e',
    messagingSenderId: '596845297819',
    projectId: 'laundromate-2e111',
    storageBucket: 'laundromate-2e111.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBfIkm32b_104BnWzf5UrN1y34ZJ5wRcBE',
    appId: '1:596845297819:ios:63fd08299b2e8d350a063e',
    messagingSenderId: '596845297819',
    projectId: 'laundromate-2e111',
    storageBucket: 'laundromate-2e111.appspot.com',
    iosClientId:
        '596845297819-qlp7mf8aoglmpocoqoa4h94ae011njog.apps.googleusercontent.com',
    iosBundleId: 'com.example.laundromate',
  );
}
